AWSTemplateFormatVersion: 2010-09-09
Description: "Master Stack Sample"
Parameters:
  VPCId:
    Type: "AWS::EC2::VPC::Id"
    Description: "VCP Id"
  KeyName:
    Type: "AWS::EC2::KeyPair::KeyName"
    Description: KeyName
  AMIId:
    Type: String
    Description: "AMI ID"
  InstanceType:
    Type: String
    Description: "Instance Type"
  SSHLocation:
    Type: String
    Description: "SSH IP Location"
Resources:
  CFNStackELB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-davidiog-s3-general.s3-ap-southeast-2.amazonaws.com/cfn/elb.yaml
      Parameters:
        VPCId: !Ref VPCId
      Tags:
        -
          Key: TemplateName
          Value: elb.yaml
  CFNStackASG:
    DependsOn: CFNStackELB
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://aws-davidiog-s3-general.s3-ap-southeast-2.amazonaws.com/cfn/launchconfig-asg.yaml
      Parameters:
        VPCId: !Ref VPCId
        KeyName: !Ref KeyName
        AMIId: !Ref AMIId
        InstanceType: !Ref InstanceType
        ElasticLoadBalancer:
          Fn::GetAtt: [ CFNStackELB, Outputs.ELBName ]
        ELBSecurityGroup:
          Fn::GetAtt: [ CFNStackELB, Outputs.ELBSecurityGroupId ]
        SSHLocation: !Ref SSHLocation
      Tags:
        -
          Key: TemplateName
          Value: launchconfig-asg.yaml
