AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Startup Kit RESTful API backed by a SimpleTable (DynamoDB).
Globals:
  Function:
    Runtime: nodejs8.10
  Api:
    Cors:
      AllowMethods: '''*'''
      AllowHeaders: '''*'''
      AllowOrigin: '''*'''
Resources:
  GetAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/app.getRandom
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /getrandom
            Method: get
      CodeUri: s3://aws-davidiog-s3-general/a7704d0b118c53734b52f9acad9adab0
Outputs:
  ApiUrl:
    Description: URL of the Prod stage of the API endpoint
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
